branch-defaults:
  main:
    environment: production
environment-defaults:
  production:
    branch: null
    repository: null
global:
  application_name: ctrlbuy-webshop
  default_ec2_keyname: null
  default_platform: Corretto 17 running on 64bit Amazon Linux 2023
  default_region: eu-north-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
